export default initialRegualrDays = {
  1: {
    id: "MON",
    value: 1,
    text: "월",
    selected: false,
    startTime: null,
    endTime: null,
  },
  2: {
    id: "TUE",
    value: 2,
    text: "화",
    selected: false,
    startTime: null,
    endTime: null,
  },
  3: {
    id: "WED",
    value: 3,
    text: "수",
    selected: false,
    startTime: null,
    endTime: null,
  },
  4: {
    id: "THU",
    value: 4,
    text: "목",
    selected: false,
    startTime: null,
    endTime: null,
  },
  5: {
    id: "FRI",
    value: 5,
    text: "금",
    selected: false,
    startTime: null,
    endTime: null,
  },
  6: {
    id: "SAT",
    value: 6,
    text: "토",
    selected: false,
    startTime: null,
    endTime: null,
  },
  7: {
    id: "SUN",
    value: 7,
    text: "일",
    selected: false,
    startTime: null,
    endTime: null,
  },
};
